### ISSUE TITLE
Mask is the fastest without the additional element (and even faster when using an image direct instead of custom prop)

### ISSUE THREAD

**Issue by benfrain** [cloudfour/svg-icon-stress-test#3]
I haven't tested this outside my dev bubble yet, but I would be keen to know if others find the same...

Running this test but amending the js so that the mask variant does not include the extra visually-hidden element: https://github.com/cloudfour/svg-icon-stress-test/blob/main/public/demo.js#L37 makes mask the fastest of the techniques.

Here are my local run timings for mask with the JS amended to not include that extra element: 48.8, 44.9, 43.3, 45.1, 42.9, 45.6, 48.5, 44.7

Meanwhile, the inline SVG option gives me results in the range: 75.2, 75.8, 73.8, 74.7, 71.2, 74.1, 69, 70.1

Also, if I amend the code further, so that the mask variant is not reliant on custom props to get the image url, it seems to be faster still:

```javascript
function genericElementHtml(iconUrl, fallbackText) {
  return `<div style="-webkit-mask-image: url(${iconUrl})">  
</div>`;
}
```

Then I get results in the 36.8, 38, 31.5, 36.8, 37.9, 37.5, 37.6, 34.9, 37.9

Which, if others can replicate these results, makes me suspect/wonder a couple of things:

- the use of clip and clip-path in the visually hidden CSS is computationally expensive
- the use of custom properties as the mechanism for setting the URL for the masks is hobbling the performance

If you get chance @tylersticka I'd love to have your insight here? I realise you made this a couple of years back so my apologies in advance for dragging you back here :)

**Comment by tylersticka** [comment]
Thanks, Ben!

I'm not in a spot where I can dig in quite yet, but I thought I'd ask two questions in advance:

1. Were you using an alternative technique for fallback text? It's important to me philosophically that we compare these techniques with accessibility fallbacks, because relative accessibility of the techniques should be an important decision-making factor.
2. Were you running the tests across browsers, or was there a specific browser in your dev bubble you were focused on?

**Comment by benfrain** [comment]
> Thanks, Ben!
> 
> I'm not in a spot where I can dig in quite yet, but I thought I'd ask two questions in advance:
> 
> 1. Were you using an alternative technique for fallback text? It's important to me philosophically that we compare these techniques with accessibility fallbacks, because relative accessibility of the techniques should be an important decision-making factor.

With the inline SVGs, there isn't any markup in the SVGs explaining what they are, is there??

```html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <circle cx="10.5" cy="10.5" r="7.5" fill="none" stroke-width="3"></circle>
  <line x1="17" y1="17" x2="22" y2="22" fill="none" stroke-linecap="round" stroke-width="3"></line>
</svg>
```

But it is an interesting point, while the element itself is a major contributing factor (obvs as any element has some cost, in this case necessary), the CSS that is used to hide the text causes additIonal time. If I leave the element in and remove the utility class I get improvements.

> 2. Were you running the tests across browsers, or was there a specific browser in your dev bubble you were focused on?

Results themselves vary across browser but the gains seem relative (only tried latest stable Safari/Chrome).

On balance, probably nothing worth thinking about further here. The test we had internally that led me down this path was missing any kind of accessibility fallback, hence giving mask a significant perceived gain over the others (not apples v apples). 

Thanks for taking a look.

**Comment by tylersticka** [comment]
> With the inline SVGs, there isn't any markup in the SVGs explaining what they are, is there??

Good point, I should add `<title>` to these! Or at least to the example SVGs. I doubt it'll have a big impact, but it'd be good to confirm.

> If I leave the element in and remove the utility class I get improvements.

I think what I'd try is having an _adjacent_ fallback element (rather than a nested one). Maybe the masking technique is _particularly_ impacted because it's applying the mask to the weirdo visually-hidden hackery?

Thanks for the info, it'll be helpful next time I take a look at this!
